# Copyright (c) 2022 OpenFaaS Ltd
name: 'block-with-tmux'
description: 'block-with-tmux'
branding:
  icon: 'arrow-right-circle'
  color: 'gray-dark'
runs:
    using: 'composite'
    steps:
      - name: Install tmux
        shell: bash
        id: install-tmux
        run: |
           sudo apt update && sudo apt install -qy openssh-server tmux
      - name: Block until tmux session is closed
        shell: bash
        id: tmux-wait-until-closed
        run: |
          echo "#!/bin/bash" >> /usr/local/bin/unblock
          echo "tmux kill-session" >> /usr/local/bin/unblock
          
          chmod +x /usr/local/bin/unblock
          
          cat << EOF | sudo tee /etc/motd
          ╺┳┓┏━╸┏┓ ╻ ╻┏━╸   ┏━┓┏━╸┏━┓┏━┓╻┏━┓┏┓╻
           ┃┃┣╸ ┣┻┓┃ ┃┃╺┓   ┗━┓┣╸ ┗━┓┗━┓┃┃ ┃┃┗┫
          ╺┻┛┗━╸┗━┛┗━┛┗━┛   ┗━┛┗━╸┗━┛┗━┛╹┗━┛╹ ╹
          
          A tmux session is running in the background, you can attach with 
          "tmux attach".
          
          To stop this host, run "unblock" or "tmux kill-session".
          
          EOF

          tmux new-session -d -s debug
          
          # Blocks until someone has attached to the session and closed it
          tmux wait-for channel
