# Copyright (c) 2022 OpenFaaS Ltd
name: 'block-with-tmux'
description: 'block-with-tmux'
branding:
  icon: 'arrow-right-circle'
  color: 'gray-dark'
runs:
    using: 'composite'
    steps:
      - name: Install tmux
        shell: bash
        id: install-tmux
        run: |
           sudo apt update && sudo apt install -qy openssh-server tmux
      - name: Block until tmux session is closed
        shell: bash
        id: waituntilclosed
        run: |
          cat << EOF | sudo tee /etc/motd
          ╺┳┓┏━╸┏┓ ╻ ╻┏━╸   ┏━┓┏━╸┏━┓┏━┓╻┏━┓┏┓╻
           ┃┃┣╸ ┣┻┓┃ ┃┃╺┓   ┗━┓┣╸ ┗━┓┗━┓┃┃ ┃┃┗┫
          ╺┻┛┗━╸┗━┛┗━┛┗━┛   ┗━┛┗━╸┗━┛┗━┛╹┗━┛╹ ╹
          
          You're in a debug session, which is blocked until 
          a tmux session we started for you gets closed.
          
          You can attach to the session with "tmux attach"
          
          To resume the action, type "exit" into "tmux" or
          "tmux kill-session"

          EOF

          tmux new-session -d -s debug
          
          # Blocks until someone has attached to the session and closed it
          tmux wait-for channel
